# Generated by Django 3.2.7 on 2009-01-01 02:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidoes', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('titre', models.CharField(max_length=30)),
                ('contenu', models.TextField()),
                ('auteur', models.CharField(max_length=30)),
                ('date_publication', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('planning_des_activités', models.FileField(blank=True, max_length=30, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('discipline', models.CharField(max_length=30)),
                ('auteur', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('support', models.CharField(max_length=10)),
                ('duree', models.PositiveSmallIntegerField()),
                ('support_cours', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='CVProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_diplomes', models.CharField(max_length=30)),
                ('annee_obtension_diplome', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='année invalide', regex='^\\d{4}$')])),
                ('ecole_obtension_diplome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('diplome', models.CharField(max_length=30)),
                ('langue', models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais')], default='FR', max_length=2)),
            ],
            options={
                'verbose_name': 'cycle',
                'verbose_name_plural': 'cycles',
            },
        ),
        migrations.CreateModel(
            name='DomaineEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDeTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_journee', models.BooleanField(default=True)),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.PositiveIntegerField(blank=True, default=0, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('noms', models.CharField(max_length=30)),
                ('prenoms', models.CharField(max_length=30)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=30)),
                ('sexe', models.CharField(choices=[('MASCULIN', 'Masculin'), ('FEMININ', 'Feminin')], default='MASCULIN', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('nationalite', models.CharField(default='Camerounaise', max_length=30)),
                ('numero_CNI', models.CharField(max_length=30)),
                ('numero_telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Mauvais format de numéro', regex='^(\\+?\\(?237\\)?)?[ ]?6([ -/.]?(\\d){2}){4}$')])),
                ('statut', models.BooleanField(default=False)),
                ('ancienne_ecole', models.CharField(blank=True, max_length=30, null=True)),
                ('cantine', models.BooleanField(default=True)),
                ('transport', models.BooleanField(default=True)),
                ('developpment_password', models.CharField(max_length=30)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.club')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.cycle')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('programme', models.TextField(blank=True, null=True)),
                ('credit', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')])),
                ('domaine', models.ManyToManyField(to='direction.DomaineEtude')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
            },
        ),
        migrations.CreateModel(
            name='MenuCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petit_dejeuner', models.CharField(max_length=30, verbose_name='le petit dejeuner de chaque jour')),
                ('image_petit_dejeuner', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image du petit dejeuner')),
                ('image_lundi', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image du menu dejeuner Lundi ')),
                ('image_mardi', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image du menu dejeuner Mardi')),
                ('image_mercredi', models.ImageField(null=True, upload_to='', verbose_name='image du menu dejeuner Mercredi')),
                ('image_jeudi', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image du menu dejeuner Jeudi')),
                ('image_vendredi', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image du menu dejeuner Vendredi')),
                ('image_samedi', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image du menu dejeuner Samedi ')),
                ('lundi', models.CharField(max_length=30, verbose_name='menu dejeuner du Lundi')),
                ('mardi', models.CharField(max_length=30, verbose_name='menu dejeuner du Mardi')),
                ('mercredi', models.CharField(max_length=30, verbose_name='menu dejeuner du Mercredi')),
                ('jeudi', models.CharField(max_length=30, verbose_name='menu dejeuner du Jeudi')),
                ('vendredi', models.CharField(max_length=30, verbose_name='menu dejeuner du Vendredi')),
                ('samedi', models.CharField(max_length=30, verbose_name='menu dejeuner du Samedi')),
            ],
            options={
                'verbose_name': 'menu de la cantine',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('noms', models.CharField(max_length=30)),
                ('prenoms', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_naissance', models.DateField(null=True)),
                ('nationalite', models.CharField(blank=True, max_length=30)),
                ('numero_CNI', models.CharField(max_length=30)),
                ('profession_tuteur', models.CharField(max_length=20)),
                ('numero_telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Mauvais format de numéro', regex='^(\\+?\\(?237\\)?)?[ ]?6([ -/.]?(\\d){2}){4}$')])),
            ],
            options={
                'verbose_name': 'Tuteur',
                'verbose_name_plural': 'Tuteurs',
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('matricule', models.PositiveIntegerField(blank=True, default=0, unique=True)),
                ('noms', models.CharField(max_length=30)),
                ('prenoms', models.CharField(max_length=30)),
                ('date_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('numero_telephone', models.PositiveSmallIntegerField(validators=[django.core.validators.RegexValidator(message='Mauvais format de numéro', regex='^(\\+?\\(?237\\)?)?[ ]?6([ -/.]?(\\d){2}){4}$')])),
                ('nationalite', models.CharField(default='Camerounaise', max_length=30)),
                ('numero_CNI', models.CharField(max_length=30)),
                ('developpment_password', models.CharField(max_length=30)),
                ('cv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction.cvprofesseur')),
                ('domaine', models.ManyToManyField(to='direction.DomaineEtude')),
                ('emploi_de_temps', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction.emploidetemps')),
                ('profil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=30)),
                ('prenoms', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('debut_matin', models.TimeField(blank=True, null=True, verbose_name="début de l'heure de passage du bus le matin")),
                ('fin_matin', models.TimeField(blank=True, null=True, verbose_name="fin de l'heure de passage du bus le matin")),
                ('debut_soir', models.TimeField(blank=True, null=True, verbose_name="début de l'heure de passage du bus le soir")),
                ('fin_soir', models.TimeField(blank=True, null=True, verbose_name="fin de l'heure de passage du bus le soir")),
            ],
            options={
                'verbose_name': 'transport',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('niveau', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('numero_salle', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('cours', models.ManyToManyField(blank=True, to='direction.Cours')),
                ('delegue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegue', to='direction.etudiant')),
                ('emploi_de_temps', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction.emploidetemps')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.filiere')),
            ],
            options={
                'verbose_name': 'Specialité',
                'verbose_name_plural': 'Specialités',
            },
        ),
        migrations.CreateModel(
            name='RetardProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('motif', models.CharField(max_length=50)),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.professeur')),
            ],
            options={
                'verbose_name': 'retard du professeur',
                'verbose_name_plural': 'retards du professeur',
            },
        ),
        migrations.CreateModel(
            name='RetardEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('motif', models.CharField(max_length=50)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.etudiant')),
            ],
            options={
                'verbose_name': "retard de l'étudiant",
                'verbose_name_plural': "retards de l'étudiant",
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Session normale 1')),
                ('sn2', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Session normale 2')),
                ('cc1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='controle continu 1')),
                ('cc2', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='controle continu 2')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.etudiant')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction.matiere')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
        ),
        migrations.AddField(
            model_name='matiere',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction.professeur'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.specialite'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction.parent'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='profil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.specialite'),
        ),
        migrations.CreateModel(
            name='EmploiDeTempsJounalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode1', to='direction.matiere')),
                ('periode2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode2', to='direction.matiere')),
                ('periode3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode3', to='direction.matiere')),
                ('periode4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode4', to='direction.matiere')),
                ('periode5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode5', to='direction.matiere')),
                ('periode6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode6', to='direction.matiere')),
                ('periode7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode7', to='direction.matiere')),
                ('periode8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode8', to='direction.matiere')),
                ('periode9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode9', to='direction.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='emploidetemps',
            name='jeudi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jeudi', to='direction.emploidetempsjounalier', verbose_name='jeudi'),
        ),
        migrations.AddField(
            model_name='emploidetemps',
            name='lundi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lundi', to='direction.emploidetempsjounalier', verbose_name='lundi'),
        ),
        migrations.AddField(
            model_name='emploidetemps',
            name='mardi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mardi', to='direction.emploidetempsjounalier', verbose_name='mardi'),
        ),
        migrations.AddField(
            model_name='emploidetemps',
            name='mercredi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercredi', to='direction.emploidetempsjounalier', verbose_name='mercredi'),
        ),
        migrations.AddField(
            model_name='emploidetemps',
            name='samedi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samedi', to='direction.emploidetempsjounalier', verbose_name='samedi'),
        ),
        migrations.AddField(
            model_name='emploidetemps',
            name='vendredi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendredi', to='direction.emploidetempsjounalier', verbose_name='vendredi'),
        ),
        migrations.AddField(
            model_name='club',
            name='delegue_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegue_club', to='direction.etudiant'),
        ),
        migrations.CreateModel(
            name='Cantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('noms', models.CharField(max_length=30)),
                ('prenoms', models.CharField(max_length=30)),
                ('nationalite', models.CharField(max_length=30)),
                ('numero_telephone', models.PositiveSmallIntegerField(validators=[django.core.validators.RegexValidator(message='Mauvais format de numéro', regex='^(\\+?(237))?[ -/.]6?([ -/.](\\d){2}){4}$')])),
                ('email', models.EmailField(max_length=254)),
                ('menu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction.menucantine')),
            ],
            options={
                'verbose_name': 'Cantine',
                'verbose_name_plural': 'Cantines',
            },
        ),
        migrations.CreateModel(
            name='AbsenceProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('motif', models.CharField(max_length=50)),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.professeur')),
            ],
            options={
                'verbose_name': 'Absence du professeur',
                'verbose_name_plural': 'absences du professeur',
            },
        ),
        migrations.CreateModel(
            name='AbsenceEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('motif', models.CharField(max_length=50)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.etudiant')),
            ],
            options={
                'verbose_name': "Absence de l'étudiant",
                'verbose_name_plural': "absences de l'étudiant",
            },
        ),
    ]
