# Generated by Django 3.2.7 on 2009-01-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaineetude',
            name='num',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
