# Generated by Django 3.2.7 on 2009-01-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0002_domaineetude_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaineetude',
            name='num',
        ),
    ]
