# Generated by Django 3.2.7 on 2009-01-01 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0003_remove_domaineetude_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='numero_telephone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Mauvais format de numéro', regex='^(\\+?\\(?237\\)?)?[ ]?6([ -/.]?(\\d){2}){4}$')]),
        ),
    ]
