# Generated by Django 3.2.7 on 2009-01-01 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0006_auto_20090101_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenceetudiant',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.professeur'),
        ),
    ]
