# Generated by Django 3.2.7 on 2009-01-01 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0007_absenceetudiant_professeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceetudiant',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.etudiant'),
        ),
        migrations.AlterField(
            model_name='absenceetudiant',
            name='heure_debut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='absenceetudiant',
            name='heure_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='absenceetudiant',
            name='motif',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='absenceetudiant',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.professeur'),
        ),
    ]
