# Generated by Django 3.2.7 on 2008-12-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0008_auto_20090101_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceetudiant',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
