# Generated by Django 3.2.7 on 2008-12-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0009_alter_absenceetudiant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceetudiant',
            name='date',
            field=models.DateField(),
        ),
    ]
