# Generated by Django 3.2.7 on 2009-01-01 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0010_alter_absenceetudiant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceetudiant',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence', to='direction.etudiant'),
        ),
    ]
